services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start:dev

  backend-debug:
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start:debug

  db:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

volumes:
  postgres_data:
